### ISSUE TITLE
Ett bra exempel på hur man kan utvärdera data för vädermodeller

### ISSUE THREAD

**Issue by TKlingstrom** [SGBC/weatherdata#28]
Jag tror "Technical validation"-delen är ett bra exempel på hur precisionen i väderdata kan presenteras.
https://www.nature.com/articles/sdata20146

**Comment by devRideg** [comment]
Super! Mycket som ser bekant ut i det vi gör! Tar en närmare titt imorgon!
Tack för referensen!
